export const dummyData = [
  {
    id: "p1",
    image: "/poster/poster1.png",
    price: "20,000",
    title: "CG Road , Ahmedabad ",
    category: "HOARDINGS",
    mediaType: "HOARDINGS/BILLBOARDS",
    lightingType: "FRONT-LIGHTING",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "CG ROAD, AHMEDABAD",
    landmark: "GIRISH COLD DRINK",
    facingFrom: "GIRISH COLD DRINK",
    towordsTo: "MAINROAD",
    size: "30 X 15",
    sft: 450,
    minDays: 5,
  },
  {
    id: "p2",
    image: "/poster/poster2.png",
    price: "20,000",
    title: "Nehrunagar , Ahmedabad ",
    category: "HOARDINGS",
    mediaType: "HOARDINGS/BILLBOARDS",
    lightingType: "FRONT-LIGHTING",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "CG ROAD, AHMEDABAD",
    landmark: "GIRISH COLD DRINK",
    facingFrom: "GIRISH COLD DRINK",
    towordsTo: "MAINROAD",
    size: "30 X 15",
    sft: 450,
    minDays: 4,
  },
  {
    id: "p3",
    image: "/poster/poster3.png",
    price: "20,000",
    title: "Satellite area, Ahmedabad ",
    category: "HOARDINGS",
    mediaType: "HOARDINGS/BILLBOARDS",
    lightingType: "FRONT-LIGHTING",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "CG ROAD, AHMEDABAD",
    landmark: "GIRISH COLD DRINK",
    facingFrom: "GIRISH COLD DRINK",
    towordsTo: "MAINROAD",
    size: "30 X 15",
    sft: 450,
    minDays: 5,
  },
  {
    id: "p4",
    image: "/poster/poster4.png",
    price: "20,000",
    title: "Karnavati club road, Ahmedabad ",
    category: "HOARDINGS",
    mediaType: "HOARDINGS/BILLBOARDS",
    lightingType: "FRONT-LIGHTING",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "CG ROAD, AHMEDABAD",
    landmark: "GIRISH COLD DRINK",
    facingFrom: "GIRISH COLD DRINK",
    towordsTo: "MAINROAD",
    size: "30 X 15",
    sft: 450,
  },
  {
    id: "p5",
    image: "/poster/image.png",
    price: "20,000",
    title: "CG Road , Ahmedabad ",
    category: "HOARDINGS",
    mediaType: "HOARDINGS/BILLBOARDS",
    lightingType: "FRONT-LIGHTING",
    state: "Gujarat",
    district: "Ahmedabad",
    address: "CG ROAD, AHMEDABAD",
    landmark: "GIRISH COLD DRINK",
    facingFrom: "GIRISH COLD DRINK",
    towordsTo: "MAINROAD",
    size: "30 X 15",
    sft: 450,
    minDays: 5,
  },
];
